name: Serverless Stack deployment to Dev

on:
  push:
    branches:
      - dev-stable

env:
  STAGE: dev
  API_VERSION: v1
  ENVIRONMENT: dev
  REGION: us-east-1
  APP_NAME: neighbours-dev
  ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  SECRET_ACCESS_KEYS: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Cache pnpm modules
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # Check if pnpm is installed, if not install
      - name: Install pnpm
        run: |
          if ! command -v pnpm &> /dev/null
          then
            npm install -g pnpm
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ env.REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install project dependencies
        run: pnpm install

      - name: Deploy
        run: npx sst deploy --stage ${{ env.STAGE }} --verbose
